### ISSUE TITLE
Stock part revamps extra parts with "_v2" in the name

### ISSUE THREAD

**Issue by SlipstreamZA** [shadowmage45/KSPRescuePodFix#3]
Due to some of the revamp of some of the stock parts, they now contain "_v2" at the back to retain the old look for ships that's been already built. 
The pods are that was added extra during the 1.4 to 1.6 updates are:

mk1pod_v2
mk2LanderCabin_v2

I'll be happy to submit a PR to include these in the RescuePods.cfg ?

**Comment by shadowmage45** [comment]
Sure thing -- I didn't think about the duplicated stock parts during the update.

If you would like to submit a PR, I'll merge it for the KSP 1.6 update/release.

**Comment by SlipstreamZA** [comment]
I submitted a PR for #3 and #4 in one commit, not sure if the cupola will ever be the chosen for a rescue mission though
